name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: /${{ github.event.repository.name }}
      PUBLIC_BUILDINGS_RASTER_PMTILES_URL: https://buildings.allmaps.org/buildings-raster@2x.pmtiles
      PUBLIC_BUILDINGS_VECTOR_PMTILES_URL: https://buildings.allmaps.org/buildings-vector.pmtiles
      PUBLIC_NEW_BUILDING_CLUSTERS_PMTILES_URL: https://buildings.allmaps.org/new-building-clusters-2015.pmtiles
      PUBLIC_NEW_BUILDING_CLUSTERS_MASK_PMTILES_URL: https://buildings.allmaps.org/new-building-clusters-mask-2015.pmtiles
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate building stats
        run: pnpm count-buildings

      - name: Build app
        run: pnpm build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: app/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
